export const CATEGORIES = [
  { id: "music", label: "Music" },
  { id: "conference", label: "Conferences" },
  { id: "community", label: "Community" },
  { id: "sports", label: "Sports & Fitness" },
  { id: "food", label: "Food & Drink" },
  { id: "workshop", label: "Workshops" },
  { id: "arts", label: "Arts & Theatre" },
];

export const EVENTS = [
  {
    id: "evt-001",
    title: "Riverside Sessions: Live at Dusk",
    category: "music",
    date: "2026-08-14T19:00:00",
    venue: "Riverside Amphitheater",
    city: "Portland, OR",
    price: 38,
    capacity: 900,
    sold: 612,
    organizer: "Dusk Collective",
    image: "music1",
    blurb: "Four local acts, one stage, golden-hour views over the river.",
    trending: true,
  },
  {
    id: "evt-002",
    title: "Product-Led Growth Summit",
    category: "conference",
    date: "2026-09-02T09:00:00",
    venue: "Moscone West",
    city: "San Francisco, CA",
    price: 249,
    capacity: 1200,
    sold: 480,
    organizer: "GrowthOps Media",
    image: "conf1",
    blurb: "Two days, 40 speakers, zero fluff — how real teams grow product-led revenue.",
    trending: false,
  },
  {
    id: "evt-003",
    title: "Neighborhood Night Market",
    category: "community",
    date: "2026-07-25T17:00:00",
    venue: "5th Ave Plaza",
    city: "Austin, TX",
    price: 0,
    capacity: 2000,
    sold: 1340,
    organizer: "Austin Mutual Aid",
    image: "community1",
    blurb: "Free monthly market — local vendors, live music, kids' zone.",
    trending: true,
  },
  {
    id: "evt-004",
    title: "Sunrise Trail Half Marathon",
    category: "sports",
    date: "2026-08-30T06:30:00",
    venue: "Cascade Foothills Trailhead",
    city: "Bend, OR",
    price: 65,
    capacity: 800,
    sold: 731,
    organizer: "Foothills Running Club",
    image: "sports1",
    blurb: "13.1 miles of switchbacks and views. Aid stations every 2 miles.",
    trending: false,
  },
  {
    id: "evt-005",
    title: "Natural Wine & Small Plates",
    category: "food",
    date: "2026-07-19T18:30:00",
    venue: "The Cellar Room",
    city: "Brooklyn, NY",
    price: 55,
    capacity: 60,
    sold: 52,
    organizer: "Cellar Room Hospitality",
    image: "food1",
    blurb: "A seated tasting through six low-intervention wines, paired course by course.",
    trending: true,
  },
  {
    id: "evt-006",
    title: "Intro to Screen Printing",
    category: "workshop",
    date: "2026-08-05T13:00:00",
    venue: "Ink & Press Studio",
    city: "Chicago, IL",
    price: 85,
    capacity: 16,
    sold: 9,
    organizer: "Ink & Press",
    image: "workshop1",
    blurb: "Pull your first print on a real press. All materials included.",
    trending: false,
  },
  {
    id: "evt-007",
    title: "Midsummer Night: A Reimagining",
    category: "arts",
    date: "2026-08-21T20:00:00",
    venue: "Blackbox Theatre",
    city: "Seattle, WA",
    price: 32,
    capacity: 180,
    sold: 94,
    organizer: "Blackbox Collective",
    image: "arts1",
    blurb: "Shakespeare's comedy, restaged in a shipping-container forest.",
    trending: false,
  },
  {
    id: "evt-008",
    title: "Founders' Breakfast: Fundraising in a Cold Market",
    category: "conference",
    date: "2026-07-30T08:00:00",
    venue: "The Yard Coworking",
    city: "Denver, CO",
    price: 0,
    capacity: 50,
    sold: 41,
    organizer: "Denver Founders Guild",
    image: "conf2",
    blurb: "Small-room, off-the-record conversation with three local VCs.",
    trending: true,
  },
  {
    id: "evt-009",
    title: "Late Night Vinyl: Disco & Boogie",
    category: "music",
    date: "2026-08-08T22:00:00",
    venue: "The Basement",
    city: "Los Angeles, CA",
    price: 18,
    capacity: 250,
    sold: 210,
    organizer: "Basement Sound",
    image: "music2",
    blurb: "All vinyl, all night. Doors at 10, no re-entry.",
    trending: false,
  },
  {
    id: "evt-010",
    title: "Youth Soccer Clinic: Fall Prep",
    category: "sports",
    date: "2026-08-16T09:00:00",
    venue: "Fairview Fields",
    city: "Columbus, OH",
    price: 40,
    capacity: 120,
    sold: 68,
    organizer: "Columbus Youth Athletics",
    image: "sports2",
    blurb: "Ages 8–14. Skills stations run by high school varsity coaches.",
    trending: false,
  },
  {
    id: "evt-011",
    title: "Sourdough From Scratch",
    category: "workshop",
    date: "2026-07-27T10:00:00",
    venue: "Flour & Salt Bakery",
    city: "Minneapolis, MN",
    price: 60,
    capacity: 12,
    sold: 12,
    organizer: "Flour & Salt",
    image: "workshop2",
    blurb: "Starter maintenance, shaping, scoring — leave with a loaf and a jar of starter.",
    trending: false,
  },
  {
    id: "evt-012",
    title: "Community Mural Paint Day",
    category: "community",
    date: "2026-08-02T11:00:00",
    venue: "Elm Street Underpass",
    city: "Detroit, MI",
    price: 0,
    capacity: 300,
    sold: 118,
    organizer: "Detroit Public Arts",
    image: "community2",
    blurb: "All ages, all skill levels. Paint, brushes, and lunch provided.",
    trending: false,
  },
];

export function getEventById(id) {
  return EVENTS.find((e) => e.id === id);
}
